name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: 'Install dependencies'
        # This runs `npm install` at the root of your project, which is correct.
        run: npm install

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          # IMPORTANT: Make sure these are the EXACT names of your secrets in GitHub settings
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_339D9CEC4D954B58A3FEC5107AAA0FE0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E5E79EAE5A049B2B82EF0669971D846 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_302477D8402A4909BDDD4BD8D42F6A7A }}

      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v1
        with:
          app-name: 'PhotoShareApp'
          package: '.' # Deploy the entire project folder
